[package]
name = "moxie"
version = "0.1.0"
authors = ["James Hobin <hobinjk@gmail.com>"]
edition = "2018"

[dependencies]
nom = "^4.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
zip = "0.5.2"
